// Generated by https://quicktype.io

export interface Item {
    name: string;
    description: string;
    colloq: string;
    plaintext: string;
    into: string[];
    image: Image;
    gold: Gold;
    tags: string[];
    maps: { [key: string]: boolean };
    stats: Stats;
}

export interface Gold {
    base: number;
    purchasable: boolean;
    total: number;
    sell: number;
}

export interface Image {
    full: string;
    sprite: string;
    group: string;
    x: number;
    y: number;
    w: number;
    h: number;
}

export interface Stats {
    FlatMagicDamageMod: number;
}
