// Generated by https://quicktype.io

export interface Rune {
    id: number;
    key: string;
    icon: string;
    name: string;
    slots: Slot[];
}

export interface Slot {
    runes: RuneElement[];
}

export interface RuneElement {
    id: number;
    key: string;
    icon: string;
    name: string;
    shortDesc: string;
    longDesc: string;
}
